network:
  name: particul_net
  num_classes: '@{dataset.num_classes}'
  pretrained: False # In training pipeline:"False"; In testing pipeline:"True"
  num_gpus: '@{num_gpus}'
  checkpoint: none
  num_patterns: 1 # Number of patterns per class (dummy value for typing purpose)
  backbone:
    name: resnet18_32x32
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: True # Plug-in to pretrained classifier
    checkpoint: ./results/mnist_particul_net_conf_esti/best.pth
    num_gpus: '@{num_gpus}'
